### ISSUE TITLE
LoginMenu bypass

### ISSUE THREAD

**Issue by ollydevulder** [physi3/Fernley-Virtual-Queue#1]
It is possible to get to the `storeSelector` function through the recursive call to `loginMenu` as on line 23 onwards it reads:
```python
if response == 'esc':
    loginMenu()
user.name = response
storeSelector(user.name)
```
Thus, upon finishing the inner `loginMenu` call, the outer scope will continue and execute the lines
```python
user.name = response
storeSelector(user.name)
```
The user now has access to the `storeSelector` function and any subsequent menus.

**Comment by ollydevulder** [comment]
Note: this can be easily fixed by placing the latter code in the body of an `else` branch.

**Comment by physi3** [comment]
Issue Solved

**Comment by ollydevulder** [comment]
It's not been solved.
